name: Update spot.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  update-spot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch spot
        run: |
          curl -L "https://api.allorigins.win/raw?url=https%3A%2F%2Fapi.metals.live%2Fv1%2Fspot" > raw.json

      - name: Commit update
        run: |
          git config user.name "hammerbid-bot"
          git config user.email "bot@github.com"
          git add spot.json
          git commit -m "update spot" || exit 0
          git push
